package hu.chubby.chunkloader;

import org.bukkit.Bukkit;
import org.bukkit.Material;
import org.bukkit.OfflinePlayer;
import org.bukkit.entity.Player;
import org.bukkit.inventory.*;
import org.bukkit.inventory.meta.ItemMeta;

import java.util.*;

/** Inventory views. Every player-visible label and lore line is read through Lang. */
public final class ChunkMenu {
    private final ChubbyPlugin plugin;
    public ChunkMenu(ChubbyPlugin plugin) { this.plugin = plugin; }
    private String t(String key) { return plugin.lang().text("gui." + key); }
    private String t(String key, Map<String, String> values) { return plugin.lang().text("gui." + key, values); }
    private List<String> l(String key) { return plugin.lang().lore("gui." + key, Map.of()); }
    private List<String> l(String key, Map<String, String> values) { return plugin.lang().lore("gui." + key, values); }
    private String grade(ChunkLoadEstimate value) { return plugin.lang().text("grades." + value.grade()); }
    private String priority(int value) { return plugin.priorityName(value); }

    public void open(Player player) { dashboard(player); }
    public void dashboard(Player player) {
        ChunkKey key = ChunkKey.of(player.getLocation().getChunk()); boolean selected = plugin.store().contains(key);
        MenuHolder h = holder(MenuHolder.View.DASHBOARD, 0, "", key, "dashboard.title", 54); Inventory i = h.getInventory(); frame(i, t("dashboard.header"));
        i.setItem(4, item(Material.NETHER_STAR, t("dashboard.status"), l("dashboard.status-lore", Map.of("owned", "" + plugin.store().count(player.getUniqueId()), "limit", "" + plugin.maxChunks(), "selected", "" + plugin.store().all().size(), "tps", String.format(Locale.ROOT, "%.2f", plugin.currentTps()), "protection", t(plugin.isLoadProtected() ? "common.protected" : "common.healthy"))), true));
        i.setItem(10, item(selected ? Material.REDSTONE_BLOCK : Material.EMERALD_BLOCK, t(selected ? "dashboard.disable" : "dashboard.enable"), l("dashboard.current-lore", Map.of("chunk", plugin.format(key))), true));
        i.setItem(12, item(Material.ANVIL, t("dashboard.manage"), l("dashboard.manage-lore"), true)); i.setItem(14, item(Material.ENDER_EYE, t("dashboard.visualize"), l("dashboard.visualize-lore")));
        i.setItem(16, item(Material.LODESTONE, t("dashboard.chunks"), l("dashboard.chunks-lore", Map.of("count", "" + plugin.store().count(player.getUniqueId()))), true)); i.setItem(28, item(Material.CHEST, t("dashboard.groups"), l("dashboard.groups-lore", Map.of("count", "" + plugin.store().groups(player.getUniqueId()).size())), true));
        i.setItem(30, item(Material.COMPASS, t("dashboard.search"), l("dashboard.search-lore"))); i.setItem(32, item(Material.BOOK, t("dashboard.help"), l("dashboard.help-lore")));
        if (player.hasPermission("chubby.admin")) { i.setItem(34, item(Material.FILLED_MAP, t("dashboard.map"), l("dashboard.map-lore"), true)); i.setItem(36, item(Material.COMPARATOR, t("dashboard.diagnostics"), l("dashboard.diagnostics-lore"), true)); }
        i.setItem(49, item(Material.BARRIER, t("common.close"), l("common.close-lore"))); show(player, i);
    }
    public void groups(Player p) { MenuHolder h=holder(MenuHolder.View.GROUP_LIST,0,"",null,"groups.title",54); Inventory i=h.getInventory(); frame(i,t("groups.header")); i.setItem(4,item(Material.CHEST,t("groups.summary"),l("groups.summary-lore"),true)); int slot=10; for(String g:plugin.store().groups(p.getUniqueId())) { if(slot>43) break; long n=plugin.store().ownedBy(p.getUniqueId()).stream().filter(k->plugin.store().group(k).equals(g)).count(); boolean paused=plugin.store().ownedBy(p.getUniqueId()).stream().filter(k->plugin.store().group(k).equals(g)).findFirst().map(plugin.store()::isGroupPaused).orElse(false); i.setItem(slot,item(paused?Material.RED_SHULKER_BOX:Material.CHEST,t("groups.entry",Map.of("group",g)),l("groups.entry-lore",Map.of("count",""+n,"state",t(paused?"common.paused":"common.active"))),!paused)); h.groupSlots().put(slot++,g); } if(h.groupSlots().isEmpty())i.setItem(22,item(Material.BOOK,t("groups.empty"),l("groups.empty-lore"))); i.setItem(49,item(Material.SPECTRAL_ARROW,t("common.back"),List.of()));show(p,i); }
    public void diagnostics(Player p) { MenuHolder h=holder(MenuHolder.View.DIAGNOSTICS,0,"",null,"diagnostics.title",54);Inventory i=h.getInventory();frame(i,t("diagnostics.header"));long active=plugin.store().all().keySet().stream().filter(k->!plugin.isChunkSuspended(k)).count();i.setItem(4,item(Material.COMPARATOR,t("diagnostics.status"),l("diagnostics.status-lore",Map.of("tps",String.format(Locale.ROOT,"%.2f",plugin.currentTps()),"selected",""+plugin.store().all().size(),"active",""+active,"paused",""+(plugin.store().all().size()-active))),true));int s=19;for(ChunkKey k:plugin.store().all().keySet().stream().sorted((a,b)->Integer.compare(plugin.estimate(b).score(),plugin.estimate(a).score())).limit(5).toList()){ChunkLoadEstimate e=plugin.estimate(k);i.setItem(s,item(Material.REPEATER,t("diagnostics.chunk",Map.of("chunk",plugin.format(k))),l("diagnostics.chunk-lore",Map.of("grade",grade(e),"score",""+e.score(),"entities",""+e.entities(),"hoppers",""+e.hoppers())),e.score()>=40));h.chunkSlots().put(s++,k);}i.setItem(49,item(Material.SPECTRAL_ARROW,t("common.back"),List.of()));show(p,i); }
    public void help(Player p) { MenuHolder h=holder(MenuHolder.View.HELP,0,"",null,"help.title",54);Inventory i=h.getInventory();frame(i,t("help.header"));i.setItem(11,item(Material.EMERALD_BLOCK,t("help.player"),l("help.player-lore"),true));i.setItem(13,item(Material.CHEST,t("help.groups"),l("help.groups-lore"),true));i.setItem(15,item(Material.COMPARATOR,t("help.admin"),l(p.hasPermission("chubby.admin")?"help.admin-lore":"help.admin-denied")));i.setItem(49,item(Material.SPECTRAL_ARROW,t("common.back"),List.of()));show(p,i); }
    public void confirmDelete(Player p,ChunkKey k,int page,String filter){MenuHolder h=holder(MenuHolder.View.CONFIRM_DELETE,page,filter,k,"confirm.title",27);Inventory i=h.getInventory();frame(i,t("confirm.header"));i.setItem(11,item(Material.LIME_CONCRETE,t("confirm.yes"),l("confirm.yes-lore"),true));i.setItem(13,item(Material.PAPER,t("confirm.chunk",Map.of("chunk",plugin.format(k))),l("confirm.chunk-lore")));i.setItem(15,item(Material.RED_CONCRETE,t("confirm.no"),l("confirm.no-lore")));show(p,i);}
    public void open(Player p,int requested,String filter){String f=filter==null?"":filter.trim().toLowerCase(Locale.ROOT);List<ChunkKey> list=plugin.store().ownedBy(p.getUniqueId()).stream().filter(k->matches(k,f)).toList();int size=plugin.guiItemsPerPage(), pages=Math.max(1,(int)Math.ceil(list.size()/(double)size)),page=Math.max(0,Math.min(requested,pages-1));MenuHolder h=holder(MenuHolder.View.LIST,page,f,null,"browser.title",54);Inventory i=h.getInventory();frame(i,t("browser.header",Map.of("page",""+(page+1),"pages",""+pages)));ChunkKey current=ChunkKey.of(p.getLocation().getChunk());boolean selected=plugin.store().contains(current);i.setItem(0,item(selected?Material.REDSTONE_BLOCK:Material.EMERALD_BLOCK,t(selected?"dashboard.disable":"dashboard.enable"),l("dashboard.current-lore",Map.of("chunk",plugin.format(current))),true));i.setItem(1,item(Material.ENDER_EYE,t("dashboard.visualize"),l("dashboard.visualize-lore")));i.setItem(3,item(Material.COMPASS,t("dashboard.search"),l("browser.search-lore",Map.of("filter",f.isBlank()?t("common.none"):f))));i.setItem(7,item(Material.ANVIL,t("dashboard.manage"),l("dashboard.manage-lore"),true));if(p.hasPermission("chubby.admin"))i.setItem(8,item(Material.FILLED_MAP,t("dashboard.map"),l("dashboard.map-lore"),true));for(int x=0;x<size&&page*size+x<list.size();x++){ChunkKey k=list.get(page*size+x);String g=plugin.store().group(k);i.setItem(9+x,item(Material.LODESTONE,t("browser.chunk",Map.of("chunk",plugin.format(k))),l("browser.chunk-lore",Map.of("group",g.isBlank()?t("common.none"):g,"priority",priority(plugin.store().priority(k)),"state",t(plugin.isChunkSuspended(k)?"common.paused":"common.active"))),!plugin.isChunkSuspended(k)));h.chunkSlots().put(9+x,k);}i.setItem(45,item(Material.SPECTRAL_ARROW,t("browser.previous"),l(page==0?"browser.first-page":"browser.previous-lore")));i.setItem(49,item(Material.BARRIER,t("common.close"),l("common.close-lore")));i.setItem(53,item(Material.SPECTRAL_ARROW,t("browser.next"),l(page+1>=pages?"browser.last-page":"browser.next-lore")));show(p,i);}
    public void manage(Player p){ChunkKey k=ChunkKey.of(p.getLocation().getChunk());MenuHolder h=holder(MenuHolder.View.MANAGE,0,"",k,"manage.title",54);Inventory i=h.getInventory();frame(i,t("manage.header"));if(!plugin.store().contains(k)){i.setItem(22,item(Material.BARRIER,t("manage.unselected"),l("manage.unselected-lore")));i.setItem(49,item(Material.SPECTRAL_ARROW,t("common.back"),List.of()));show(p,i);return;}String g=plugin.store().group(k);i.setItem(4,item(Material.LODESTONE,t("manage.chunk",Map.of("chunk",plugin.format(k))),l("manage.chunk-lore",Map.of("group",g.isBlank()?t("common.none"):g,"priority",priority(plugin.store().priority(k))))));for(int n=0;n<3;n++){int slot=n==0?10:n==1?13:16;Material m=n==0?Material.COAL:n==1?Material.IRON_INGOT:Material.GOLD_INGOT;i.setItem(slot,item(m,t("manage.priority-"+n),l("manage.priority-"+n+"-lore"),plugin.store().priority(k)==n));}i.setItem(28,item(Material.BARRIER,t("manage.unlink"),l(g.isBlank()?"manage.no-group":"manage.unlink-lore")));if(!g.isBlank())i.setItem(29,item(Material.WRITABLE_BOOK,t("manage.actions"),l("manage.actions-lore"),true));i.setItem(30,item(Material.NAME_TAG,t("manage.new-group"),l("manage.new-group-lore")));int s=32,c=0;for(String name:plugin.store().groups(p.getUniqueId())){if(s>43||c++>=plugin.guiGroupsPerMenu())break;i.setItem(s,item(Material.CHEST,t("manage.group",Map.of("group",name)),l("manage.group-lore")));h.groupSlots().put(s++,name);}i.setItem(49,item(Material.SPECTRAL_ARROW,t("common.back"),List.of()));show(p,i);}
    public void groupActions(Player p,String g){MenuHolder h=holder(MenuHolder.View.GROUP,0,g,null,"group.title",27);Inventory i=h.getInventory();frame(i,t("group.header"));List<ChunkKey> keys=plugin.store().ownedBy(p.getUniqueId()).stream().filter(k->plugin.store().group(k).equals(g)).toList();boolean paused=keys.stream().findFirst().map(plugin.store()::isGroupPaused).orElse(false);i.setItem(4,item(Material.CHEST,t("group.name",Map.of("group",g)),l("group.name-lore",Map.of("count",""+keys.size(),"state",t(paused?"common.paused":"common.active"))),true));for(int n=0;n<3;n++){int s=n==0?10:n==1?13:16;Material m=n==0?Material.COAL:n==1?Material.IRON_INGOT:Material.GOLD_INGOT;i.setItem(s,item(m,t("group.priority-"+n),l("group.priority-lore")));}i.setItem(22,item(paused?Material.LIME_DYE:Material.RED_DYE,t(paused?"group.resume":"group.pause"),l("group.pause-lore"),!paused));i.setItem(18,item(Material.SPECTRAL_ARROW,t("common.back"),List.of()));show(p,i);}
    public void info(Player p,ChunkKey k,int page,String filter){MenuHolder h=holder(MenuHolder.View.INFO,page,filter,k,"info.title",27);Inventory i=h.getInventory();frame(i,t("info.header"));OfflinePlayer owner=Bukkit.getOfflinePlayer(plugin.store().owner(k));String ownerName=owner.getName()==null?owner.getUniqueId().toString():owner.getName();ChunkLoadEstimate e=plugin.estimate(k);String g=plugin.store().group(k);i.setItem(11,item(Material.LODESTONE,t("info.chunk",Map.of("chunk",plugin.format(k))),l("info.chunk-lore",Map.of("owner",ownerName,"available",t(Bukkit.getWorld(k.worldName())==null?"common.no":"common.yes"),"group",g.isBlank()?t("common.none"):g,"priority",priority(plugin.store().priority(k)),"state",t(plugin.isChunkSuspended(k)?"common.paused":"common.active"))),!plugin.isChunkSuspended(k)));i.setItem(13,item(Material.PAPER,t("info.technical"),l("info.technical-lore",Map.of("x",""+k.x(),"z",""+k.z(),"minx",""+(k.x()<<4),"maxx",""+((k.x()<<4)+15),"minz",""+(k.z()<<4),"maxz",""+((k.z()<<4)+15))));i.setItem(14,item(Material.COMPARATOR,t("info.estimate"),l("info.estimate-lore",Map.of("grade",grade(e),"score",""+e.score(),"entities",""+e.entities(),"hoppers",""+e.hoppers(),"tiles",""+e.tileEntities())));if(p.getUniqueId().equals(plugin.store().owner(k))||p.hasPermission("chubby.admin"))i.setItem(15,item(Material.REDSTONE_BLOCK,t("info.remove"),l("info.remove-lore")));i.setItem(18,item(Material.SPECTRAL_ARROW,t("common.back"),List.of()));i.setItem(22,item(Material.BARRIER,t("common.close"),List.of()));show(p,i);}
    public void map(Player p,int x,int z){String w=p.getWorld().getName();MenuHolder h=holder(MenuHolder.View.MAP,x,""+z,null,"map.title",54);Inventory i=h.getInventory();frame(i,t("map.header"));i.setItem(4,item(Material.FILLED_MAP,t("map.center",Map.of("world",w,"x",""+x,"z",""+z)),l("map.center-lore"),true));for(int dz=-2;dz<=2;dz++)for(int dx=-3;dx<=3;dx++){ChunkKey k=new ChunkKey(w,x+dx,z+dz);boolean claimed=plugin.store().contains(k);Material m=!claimed?Material.GRAY_STAINED_GLASS_PANE:plugin.store().owner(k).equals(p.getUniqueId())?Material.LIME_STAINED_GLASS_PANE:Material.RED_STAINED_GLASS_PANE;if(dx==0&&dz==0)m=Material.GLOWSTONE;int s=(dz+3)*9+(dx+4);i.setItem(s,item(m,t("map.chunk",Map.of("x",""+k.x(),"z",""+k.z())),l(claimed?"map.claimed":"map.empty"),dx==0&&dz==0));if(claimed)h.chunkSlots().put(s,k);}i.setItem(0,item(Material.SPECTRAL_ARROW,t("map.north"),l("map.move-lore")));i.setItem(1,item(Material.SPECTRAL_ARROW,t("map.west"),l("map.move-lore")));i.setItem(7,item(Material.SPECTRAL_ARROW,t("map.east"),l("map.move-lore")));i.setItem(8,item(Material.SPECTRAL_ARROW,t("map.south"),l("map.move-lore")));i.setItem(2,item(Material.BARRIER,t("common.close"),List.of()));show(p,i);}
    private MenuHolder holder(MenuHolder.View v,int p,String f,ChunkKey k,String title,int size){return new MenuHolder(v,p,f,k,t(title),size);} private boolean matches(ChunkKey k,String f){return f.isBlank()||(k.worldName()+" "+k.x()+" "+k.z()).toLowerCase(Locale.ROOT).contains(f);} private void show(Player p,Inventory i){p.openInventory(i);p.playSound(p.getLocation(),org.bukkit.Sound.BLOCK_ENDER_CHEST_OPEN,.35F,1.4F);} private void frame(Inventory i,String head){ItemStack fill=item(Material.BLACK_STAINED_GLASS_PANE,t("common.filler"),List.of());for(int s=0;s<i.getSize();s++)i.setItem(s,fill);ItemStack line=item(Material.GRAY_STAINED_GLASS_PANE,head,List.of());for(int s=0;s<9;s++)i.setItem(s,line);for(int s=i.getSize()-9;s<i.getSize();s++)i.setItem(s,line);} private ItemStack item(Material m,String n,List<String> lore){return item(m,n,lore,false);}private ItemStack item(Material m,String n,List<String> lore,boolean glow){ItemStack stack=new ItemStack(m);ItemMeta meta=stack.getItemMeta();meta.setDisplayName(n);if(!lore.isEmpty())meta.setLore(lore);if(glow)meta.setEnchantmentGlintOverride(true);meta.addItemFlags(ItemFlag.HIDE_ENCHANTS,ItemFlag.HIDE_ATTRIBUTES);stack.setItemMeta(meta);return stack;}
}
